Repository codestates-seb/seb42_main_012, pull requests merged in 2023-03, with the labels that each got.

#1 [FE] init: 프론트 초기설정
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc.js
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.jsx
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/tailwind.config.js
Labels: FE

#4 design: 레이아웃 추가
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/BackButton.jsx
  client/src/components/GymNewest.jsx
  client/src/components/GymNewestList.jsx
  client/src/components/GymTabList.jsx
  client/src/components/HeaderTitle.jsx
  client/src/components/layout/Header.jsx
  client/src/components/layout/Main.jsx
  client/src/components/layout/Nav.jsx
  client/src/pages/GymPage.jsx
  client/tailwind.config.js
Labels: FE

#5 design: 레이아웃 css 수정
  client/.eslintrc.js
  client/.prettierrc.js
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/GymNewest.jsx
  client/src/components/HeaderTitle.jsx
  client/src/components/UI/BackButton.jsx
  client/src/components/UI/ChatButton.jsx
  client/src/components/UI/EditButton.jsx
  client/src/components/UI/HeaderTitle.jsx
  client/src/components/UI/PostButton.jsx
  client/src/components/layout/Header.jsx
  client/src/components/layout/Main.jsx
  client/src/components/layout/Nav.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/components/layouts/Main/Main.jsx
  client/src/components/layouts/MainLayout.jsx
  client/src/components/layouts/Nav/Nav.jsx
  client/src/pages/GymPage.jsx
Labels: FE

#6 design: GYM페이지 수정
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/ErrorFallback.jsx
  client/src/components/GymNewest.jsx
  client/src/components/GymNewestList.jsx
  client/src/components/Loading.jsx
  client/src/components/UI/ChatButton.jsx
  client/src/components/UI/HeartButton.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/components/layouts/Main/Main.jsx
  client/tailwind.config.js
Labels: FE

#9 design: 짐페이지 수정
  client/package-lock.json
  client/src/components/Gym.jsx
  client/src/components/GymList.jsx
  client/src/components/GymNewest.jsx
  client/src/components/GymNewestList.jsx
  client/src/components/GymTabList.jsx
  client/src/components/GymTagList.jsx
  client/src/components/ReviewScore.jsx
  client/src/components/UI/GymTag.jsx
  client/src/components/UI/StarIcon.jsx
  client/src/components/UI/TabButton.jsx
  client/src/pages/GymPage.jsx
Labels: FE

#15 design: 마이페이지 수정중
  client/src/App.jsx
  client/src/components/Board/BoardPost.jsx
  client/src/components/Board/BoardPostBody.jsx
  client/src/components/Board/BoardPostTitle.jsx
  client/src/components/Board/BoardTabList.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/GymList.jsx
  client/src/components/Gym/GymNewest.jsx
  client/src/components/Gym/GymNewestList.jsx
  client/src/components/Gym/GymTabList.jsx
  client/src/components/Gym/GymTagList.jsx
  client/src/components/My/MyAccount.jsx
  client/src/components/My/MyPageList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/BasicButton.jsx
  client/src/components/UI/DisplayName.jsx
  client/src/components/UI/EditButton.jsx
  client/src/components/UI/GymTag.jsx
  client/src/components/UI/MyPageButton.jsx
  client/src/components/UI/ProfileImg.jsx
  client/src/components/layouts/Nav/Nav.jsx
  client/src/pages/BoardDetailPage.jsx
  client/src/pages/BoardEditPage.jsx
  client/src/pages/BoardPage.jsx
  client/src/pages/BoardPostPage.jsx
  client/src/pages/GymPage.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/Login.jsx
  client/src/pages/MyDetailPage.jsx
  client/src/pages/MyPage.jsx
  client/src/pages/SignUp.jsx
Labels: FE

#22 design: 헬스장, 리뷰상세 페이지 수정 및 추가
  client/src/App.jsx
  client/src/components/Board/BoardHeaderContainer.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/GymDetailList.jsx
  client/src/components/Gym/GymDetailMainImg.jsx
  client/src/components/Gym/GymFacilities.jsx
  client/src/components/Gym/GymMap.jsx
  client/src/components/Gym/GymMapContainer.jsx
  client/src/components/Gym/GymPrice.jsx
  client/src/components/Gym/GymPriceTable.jsx
  client/src/components/Gym/GymPriceTableContainer.jsx
  client/src/components/Gym/GymReview.jsx
  client/src/components/Gym/GymReviewConmment.jsx
  client/src/components/Gym/GymReviewList.jsx
  client/src/components/Gym/GymReviewPost.jsx
  client/src/components/Gym/GymReviewTitle.jsx
  client/src/components/Gym/GymReviews.jsx
  client/src/components/Gym/StarIconContainer.jsx
  client/src/components/UI/BasicButton.jsx
  client/src/components/UI/GymNameButton.jsx
  client/src/components/UI/TextInput.jsx
  client/src/pages/GymReviewPage.jsx
  client/tailwind.config.js
Labels: FE

#23 Feat: 유저 엔티티 설계
  back/src/main/java/main012/server/user/entity/Role.java
  back/src/main/java/main012/server/user/entity/User.java
  back/src/main/java/main012/server/user/entity/UserInfo.java
Labels: BE

#29 design: 헬스장 등록 페이지 추가
  client/src/App.jsx
  client/src/components/Gym/GymDetailList.jsx
  client/src/components/Gym/GymHours.jsx
  client/src/components/Gym/GymPhoneNumber.jsx
  client/src/components/Gym/GymPostAddress.jsx
  client/src/components/Gym/GymPostFacilities.jsx
  client/src/components/Gym/GymPostHours.jsx
  client/src/components/Gym/GymPostImage.jsx
  client/src/components/Gym/GymPostName.jsx
  client/src/components/Gym/GymPostPhoneNumber.jsx
  client/src/components/Gym/GymPostPrice.jsx
  client/src/components/Gym/GymPostTrainer.jsx
  client/src/components/UI/PostButton.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/BoardDetailPage.jsx
  client/src/pages/GymPage.jsx
  client/src/pages/GymPostPage.jsx
Labels: FE

#31 Feat: Community Entity 클래스 작성
  back/src/main/java/main012/server/community/entity/Community.java
  back/src/main/java/main012/server/community/entity/CommunityBookmark.java
  back/src/main/java/main012/server/community/entity/CommunityComment.java
  back/src/main/java/main012/server/community/entity/Tab.java
  back/src/main/java/main012/server/user/entity/User.java
Labels: BE

#36 Feat: Image 기능 구현
  .github/workflows/gradle.yml
  back/build.gradle
  back/src/main/java/main012/server/community/entity/Community.java
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
  back/src/main/java/main012/server/image/config/S3Config.java
  back/src/main/java/main012/server/image/entity/CommunityImage.java
  back/src/main/java/main012/server/image/entity/GymImage.java
  back/src/main/java/main012/server/image/entity/Image.java
  back/src/main/java/main012/server/image/repository/ImageRepository.java
  back/src/main/java/main012/server/image/service/ImageService.java
  back/src/main/java/main012/server/user/entity/Role.java
  back/src/main/java/main012/server/user/entity/User.java
  back/src/main/java/main012/server/user/entity/UserInfo.java
Labels: BE

#41 design: GYM 페이지 수정진행중
  client/src/components/Board/BoardSearchContainer.jsx
  client/src/components/Gym/GymHours.jsx
  client/src/components/Gym/GymHoursContainer.jsx
  client/src/components/Gym/GymPriceTableContainer.jsx
  client/src/components/Gym/GymReviewPost.jsx
Labels: FE

#43 design: 목업완성
  client/package-lock.json
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/GymNewestList.jsx
  client/src/components/Gym/GymPostAddress.jsx
  client/src/components/Gym/GymPostDetailPrice.jsx
  client/src/components/Gym/GymPostFacilities.jsx
  client/src/components/Gym/GymPostFacilitiesTagList.jsx
  client/src/components/Gym/GymPostHours.jsx
  client/src/components/Gym/GymPostImage.jsx
  client/src/components/Gym/GymPostName.jsx
  client/src/components/Gym/GymPostPhoneNumber.jsx
  client/src/components/Gym/GymPostPrice.jsx
  client/src/components/Gym/GymTabList.jsx
  client/src/components/Gym/GymTagList.jsx
  client/src/components/UI/GymPostTag.jsx
  client/src/pages/GymPostPage.jsx
Labels: FE

#45 design: 목업 수정
  client/src/components/Gym/GymHours.jsx
  client/src/components/Gym/GymPhoneNumber.jsx
  client/src/components/Gym/GymPhoneNumberContainer.jsx
  client/src/components/Gym/GymPostAddress.jsx
  client/src/components/Gym/GymPostDetailPrice.jsx
  client/src/components/Gym/GymPostFacilitiesTagList.jsx
  client/src/components/Gym/GymPostHours.jsx
  client/src/components/Gym/GymPostImage.jsx
  client/src/components/Gym/GymPostName.jsx
  client/src/components/Gym/GymPostPhoneNumber.jsx
  client/src/components/Gym/GymPostPrice.jsx
  client/src/components/UI/BackButton.jsx
  client/src/components/UI/CompleteButton.jsx
  client/src/components/layouts/Modal/Modal.jsx
  client/src/components/layouts/More.jsx
Labels: FE

#47 design: Board 레이아웃 수정
  client/src/components/Board/Board.jsx
  client/src/components/Board/BoardList.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/BoardPage.jsx
Labels: FE

#53 Chore: 더미데이터추가 및 관련 라이브러리 설치
  .vscode/settings.json
  client/.env
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/mockServiceWorker.js
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/pikachu.JPG
  client/src/components/UI/Gym/GymNameButton.jsx
  client/src/dummyData.jsx
  client/src/index.js
  client/src/mocks/dummyData.js
  client/src/mocks/handlers.js
  client/src/mocks/worker.js
  client/tailwind.config.js
Labels: FE

#55 chore: 더미데이터 수정
  client/src/components/Gym/Hours/HoursContainer.jsx
  client/src/components/Gym/Price/PriceTableContainer.jsx
  client/src/mocks/dummyData.js
  client/src/mocks/handlers.js
Labels: FE

#59 feat: Board post 페이지 에디터 추가
  client/src/components/Board/Post/PostBody.jsx
Labels: FE

#60 feat: 헬스장 페이지 수정
  client/package-lock.json
  client/package.json
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/List/GymTagList.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/components/ScrollToTop.jsx
  client/src/components/UI/Gym/GymTag.jsx
  client/src/index.js
  client/src/mocks/dummyData.js
  client/src/mocks/handlers.js
  client/src/pages/Gym/Gym.jsx
  client/tailwind.config.js
Labels: FE

#64 feat: 헬스장 페이지 기능추가
  client/package-lock.json
  client/src/components/Gym/Detail/DetailHeader.jsx
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Detail/DetailMainImg.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/GymFacilities.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewScore.jsx
  client/src/components/Gym/Review/ReviewTitle.jsx
  client/src/components/Gym/StarIconContainer.jsx
  client/src/components/UI/HeartContainer.jsx
  client/src/components/UI/Icon/StarOutlineIcon.jsx
  client/src/mocks/dummyData.jsx
  client/src/mocks/handlers.jsx
  client/src/mocks/worker.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/state/useStore.jsx
Labels: FE

#67 feat: 리뷰 작성 기능 추가
  client/package-lock.json
  client/package.json
  client/src/components/Board/Board.jsx
  client/src/components/Board/Comment/CommentList.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/UI/Gym/GymNameButton.jsx
  client/src/mocks/handlers.jsx
  client/src/pages/Gym/GymDetail.jsx
Labels: FE

#75 feat: 헬스장 등록 페이지 일부 구현
  client/.env
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/assets/images/pikachu.JPG
  client/src/components/Gym/Detail/DetailHeader.jsx
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Hours/Hours.jsx
  client/src/components/Gym/Hours/HoursContainer.jsx
  client/src/components/Gym/Phone/PhoneNumber.jsx
  client/src/components/Gym/Phone/PhoneNumberContainer.jsx
  client/src/components/Gym/Post/PostDetailPrice.jsx
  client/src/components/Gym/Post/PostFacilities.jsx
  client/src/components/Gym/Post/PostFacilitiesTagList.jsx
  client/src/components/Gym/Post/PostHours.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Post/PostName.jsx
  client/src/components/Gym/Post/PostPhoneNumber.jsx
  client/src/components/Gym/Post/PostPrice.jsx
  client/src/components/Gym/Price/Price.jsx
  client/src/components/Gym/Price/PriceTableContainer.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/Gym/StarIconChoiceContainer.jsx
  client/src/components/UI/Button/BackButton.jsx
  client/src/components/UI/Gym/GymPostTag.jsx
  client/src/components/UI/HeartContainer.jsx
  client/src/components/UI/Today.jsx
  client/src/mocks/handlers.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Gym/GymPost.jsx
Labels: FE

#76 feat: 주소검색api 구현
  client/package-lock.json
  client/package.json
  client/src/components/Gym/Post/PostAddress.jsx
  client/src/components/Gym/Post/PostFacilitiesTagList.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Post/PostName.jsx
  client/src/components/UI/Postcode.jsx
  client/src/pages/Gym/GymPost.jsx
Labels: FE

#78 feat: 마이페이지 기능구현중, .env file 제거
  client/.env
  client/package-lock.json
  client/package.json
  client/src/components/Board/Tab/TabList.jsx
  client/src/components/Gym/Detail/DetailHeader.jsx
  client/src/components/Gym/List/GymTabList.jsx
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/Detail/MyDetailTitle.jsx
  client/src/components/My/MyPageList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/LogoutButton.jsx
  client/src/components/UI/Button/MyPageButton.jsx
  client/src/components/UI/Button/TabButton.jsx
  client/src/components/UI/DisplayName/DisplayName.jsx
  client/src/components/UI/More.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/mocks/dummyData.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardDetail.jsx
  client/src/pages/My/MyDetail.jsx
  client/src/state/useStore.jsx
  client/src/utils/validate.js
Labels: FE

#77 Feat: 회원 탈퇴, AccessToken 재발급
  back/src/main/java/main012/server/auth/controller/AuthController.java
  back/src/main/java/main012/server/auth/filter/JwtAuthenticationFilter.java
  back/src/main/java/main012/server/auth/jwt/JwtTokenizer.java
  back/src/main/java/main012/server/auth/service/AuthService.java
  back/src/main/java/main012/server/auth/service/MemberDetailsService.java
  back/src/main/java/main012/server/exception/ExceptionCode.java
  back/src/main/java/main012/server/user/controller/MemberController.java
  back/src/main/java/main012/server/user/dto/MemberRequestDto.java
  back/src/main/java/main012/server/user/entity/Member.java
  back/src/main/java/main012/server/user/service/MemberService.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Labels: BE

#82 feat: 지도, 위치기반 기능 구현
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Detail/Location.jsx
  client/src/components/Gym/Map/Map.jsx
  client/src/components/Gym/Map/MapContainer.jsx
  client/src/components/Gym/Review/ReviewScore.jsx
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/UI/Postcode.jsx
  client/src/pages/Home/Home.jsx
Labels: FE

#90 feat: env 수정
  client/public/index.html
Labels: FE

#91 feat: 카카오맵 KEY관련 수정
  client/public/index.html
Labels: FE

#89 Feat: 마이페이지 조회
  back/src/main/java/main012/server/advice/GlobalExceptionAdvice.java
  back/src/main/java/main012/server/auth/filter/JwtVerificationFilter.java
  back/src/main/java/main012/server/auth/handler/MemberAuthenticationEntryPoint.java
  back/src/main/java/main012/server/auth/jwt/JwtTokenizer.java
  back/src/main/java/main012/server/auth/resolver/MemberArgumentResolver.java
  back/src/main/java/main012/server/common/dto/SingleResponseDto.java
  back/src/main/java/main012/server/community/repository/CommentRepository.java
  back/src/main/java/main012/server/community/repository/CommunityBookmarkRepository.java
  back/src/main/java/main012/server/community/repository/CommunityRepository.java
  back/src/main/java/main012/server/community/service/CommentService.java
  back/src/main/java/main012/server/exception/ExceptionCode.java
  back/src/main/java/main012/server/gym/controller/GymReviewController.java
  back/src/main/java/main012/server/gym/repository/GymBookmarkRepository.java
  back/src/main/java/main012/server/gym/repository/GymReviewRepository.java
  back/src/main/java/main012/server/user/controller/MemberController.java
  back/src/main/java/main012/server/user/dto/MemberInfoDto.java
  back/src/main/java/main012/server/user/dto/MemberResponseDto.java
  back/src/main/java/main012/server/user/mapper/MemberMapper.java
  back/src/main/java/main012/server/user/service/MemberService.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
  back/src/main/resources/application.yml
Labels: BE

#100 feat: 엑시오스 인스턴스 생성
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/List/GymTagList.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/index.js
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Home/Home.jsx
  client/src/state/useStore.jsx
  client/src/utils/api.jsx
Labels: FE

#102 feat: 엑시오스 인스턴스 수정
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Home/Home.jsx
  client/src/utils/api.jsx
Labels: FE

#103 feat: 마이페이지 구현중
  client/package-lock.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/Board/Board.jsx
  client/src/components/Board/Comment/CommentHeader.jsx
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/Detail/MyDetailTitle.jsx
  client/src/components/My/MyPageList.jsx
  client/src/components/My/Password/CheckPasswordList.jsx
  client/src/components/My/Password/PasswordList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/EditButton.jsx
  client/src/components/UI/Button/MyPageButton.jsx
  client/src/components/UI/DisplayName/DisplayName.jsx
  client/src/components/UI/ProfileImg/ProfileImg.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/index.js
  client/src/mocks/dummyData.jsx
  client/src/mocks/handlers.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/My/MyDetail.jsx
  client/src/pages/My/MyPage.jsx
  client/src/state/useStore.jsx
Labels: FE

#104 feat: 엑시오스 인스턴스 수정...
  client/src/pages/Home/Home.jsx
  client/src/utils/api.jsx
Labels: FE

#106 feat: 엑시오스 인터셉터 기능수정
  client/src/components/Login/Login.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Home/Home.jsx
  client/src/utils/api.jsx
Labels: FE

#107 feat: 엑시오스 인스턴스 수정
  client/src/components/Login/Login.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/utils/api.jsx
Labels: FE

#108 feat: 마이페이지 기능구현중
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/MyPageList.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/My/MyPage.jsx
Labels: FE

#116 Feat: 회원 validation 추가
  back/src/main/java/main012/server/user/controller/MemberController.java
  back/src/main/java/main012/server/user/dto/MemberRequestDto.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Labels: BE

#121 feat : 게시글 조회수 업데이트 추가
  back/src/main/java/main012/server/community/entity/Community.java
  back/src/main/java/main012/server/community/repository/CommunityRepository.java
  back/src/main/java/main012/server/community/service/CommunityService.java
Labels: BE

#127 feat: msw 수정
  client/package-lock.json
  client/package.json
  client/src/components/Gym/Post/PostAddress.jsx
  client/src/components/Gym/Post/PostDetailPrice.jsx
  client/src/components/Gym/Post/PostHours.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Post/PostName.jsx
  client/src/components/Gym/Post/PostPhoneNumber.jsx
  client/src/components/Gym/Post/PostPrice.jsx
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/UI/Postcode.jsx
  client/src/mocks/GymDummyData.jsx
  client/src/mocks/dummyData.jsx
  client/src/mocks/handlers.jsx
  client/src/pages/Gym/GymPost.jsx
  client/src/state/useStore.jsx
  client/tailwind.config.js
Labels: FE

#129 feat: 게시글 상세조회 서버연결
  client/src/components/Board/Board.jsx
  client/src/components/Board/Detail/BoardDetail.jsx
  client/src/pages/Board/BoardDetail.jsx
  client/src/state/boardStore.jsx
Labels: FE

#130 feat: 마이페이지 구현중
  client/package-lock.json
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/EditButton.jsx
  client/src/components/UI/ProfileImg/ProfileImg.jsx
Labels: FE

#132 feat: 헬스장 기능구현
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymTagList.jsx
  client/src/components/Gym/Post/PostAddress.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewScore.jsx
  client/src/components/UI/Postcode.jsx
  client/src/index.js
  client/src/mocks/GymDummyData.jsx
  client/src/mocks/handlers.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Gym/GymPost.jsx
  client/src/pages/Gym/gymAxios.js
  client/src/state/useGymStore.jsx
Labels: FE

#133 feat: 마이페이지 기능 구현중
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/TabButton.jsx
  client/src/components/UI/ProfileImg/ProfileImg.jsx
Labels: FE

#135 feat: 헬스장 페이지 수정
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/Gym/Review/ReviewScore.jsx
  client/src/components/My/Profile.jsx
  client/src/mocks/handlers.jsx
  client/src/state/useStore.jsx
Labels: FE

#136 Fix: 헬스장 등록, 수정, 조회 로직 수정
  back/src/main/java/main012/server/exception/ExceptionCode.java
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/entity/Facility.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/repository/GymBookmarkRepository.java
  back/src/main/java/main012/server/gym/repository/GymRepository.java
  back/src/main/java/main012/server/gym/service/GymService.java
  back/src/main/java/main012/server/image/entity/GymImage.java
  back/src/main/java/main012/server/image/service/ImageService.java
Labels: BE

#137 feat: 마이페이지 프로필수정 구현중
  client/src/components/My/Password/PasswordList.jsx
  client/src/components/My/Password/PasswordNow.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/BackButton.jsx
  client/src/components/UI/Button/TabButton.jsx
  client/src/components/UI/Form/FormGroup.jsx
  client/src/context/form-group-context.jsx
  client/src/index.js
  client/src/pages/My/MyPage.jsx
  client/src/state/useMyStore.jsx
  client/src/utils/validate.js
Labels: FE

#138 feat: 헬스장 포스트 기능 구현
  client/package-lock.json
  client/src/components/Gym/Detail/DetailHeader.jsx
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Detail/DetailMainImg.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/List/GymTagList.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/components/Gym/Post/PostAddress.jsx
  client/src/components/Gym/Post/PostFacilitiesTagList.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Post/PostImageList.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewScoreList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/HeartContainer.jsx
  client/src/components/UI/Postcode.jsx
  client/src/mocks/GymDummyData.jsx
  client/src/mocks/dummyData.jsx
  client/src/mocks/handlers.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Gym/GymPost.jsx
  client/src/pages/Gym/gymAxios.js
  client/src/state/useGymStore.jsx
Labels: FE

#139 feat: 헬스장 상세페이지 수정
  client/src/components/Gym/Detail/DetailMainImg.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
Labels: FE

#141 feat: 마이페이지 프로필 수정기능 구현중
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/Password/PasswordList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/DisplayName/DisplayName.jsx
Labels: FE

#142 Fix: 프로필 수정, 마이페이지 메인 조회 수정
  back/src/main/java/main012/server/auth/config/JasyptConfig.java
  back/src/main/java/main012/server/gym/entity/GymPrice.java
  back/src/main/java/main012/server/user/controller/MemberController.java
  back/src/main/java/main012/server/user/dto/MemberRequestDto.java
  back/src/main/java/main012/server/user/dto/MemberResponseDto.java
  back/src/main/java/main012/server/user/mapper/MemberMapper.java
  back/src/main/java/main012/server/user/service/MemberService.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Labels: BE

#144 feat: 헬스장 페이지 수정
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/index.js
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Gym/GymPost.jsx
Labels: FE

#146 fix : 게시글 사진 수정 로직 추가 및 응답 수정
  back/src/main/java/main012/server/community/controller/CommentController.java
  back/src/main/java/main012/server/community/controller/CommunityController.java
  back/src/main/java/main012/server/community/dto/CommunityDto.java
  back/src/main/java/main012/server/community/entity/Community.java
  back/src/main/java/main012/server/community/mapper/CommunityMapper.java
  back/src/main/java/main012/server/community/repository/CommunityBookmarkRepository.java
  back/src/main/java/main012/server/community/service/CommentService.java
  back/src/main/java/main012/server/community/service/CommunityService.java
  back/src/main/java/main012/server/image/entity/CommunityImage.java
  back/src/main/java/main012/server/image/repository/CommunityImageRepo.java
Labels: BE

#147 feat: 헬스장 세부페이지 수정
  client/src/components/Gym/Detail/DetailMainImg.jsx
  client/src/components/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Home/Home.jsx
Labels: FE

#149 feat: 댓글 수정 구현중
  client/src/components/Board/Comment/CommentBody.jsx
  client/src/components/Board/Comment/CommentContainer.jsx
  client/src/components/Board/Comment/CommentHeader.jsx
  client/src/components/Board/Comment/CommentList.jsx
Labels: FE

#150 feat: 로그인연결 외 수정
  client/src/App.jsx
  client/src/components/Login/Login.jsx
  client/src/components/My/Detail/MyDetailTitle.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/LogoutButton.jsx
  client/src/components/UI/Button/MyPageButton.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/My/MyPage.jsx
  client/src/state/useStore.jsx
Labels: FE

#151 feat: 마이페이지 기능구현중
  client/src/components/My/Detail/MyDetailList.jsx
Labels: FE

#152 Chore: 페이지 머지
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Detail/DetailMainImg.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/components/UI/Button/BasicButton.jsx
  client/src/components/UI/Button/MoreButton.jsx
  client/src/components/UI/More.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/Gym/GymPatch.jsx
Labels: FE

#153 Fix: 마이페이지 메인 조회시 role response 추가
  back/src/main/java/main012/server/user/dto/MemberResponseDto.java
  back/src/main/java/main012/server/user/mapper/MemberMapper.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Labels: BE

#155 fix : 커뮤니티 전체 조회시 북마크 여부 확인 기능 수정
  back/src/main/java/main012/server/community/controller/CommentController.java
  back/src/main/java/main012/server/community/controller/CommunityController.java
  back/src/main/java/main012/server/community/dto/CommentDto.java
  back/src/main/java/main012/server/community/dto/CommunityDto.java
  back/src/main/java/main012/server/community/mapper/CommentMapper.java
  back/src/main/java/main012/server/community/mapper/CommunityMapper.java
  back/src/main/java/main012/server/community/service/CommentService.java
  back/src/main/java/main012/server/community/service/CommunityService.java
  back/src/main/java/main012/server/exception/ExceptionCode.java
Labels: BE

#156 feat: 커뮤니티페이지 기능 구현중
  client/src/App.jsx
  client/src/components/Board/Board.jsx
  client/src/components/Board/BoardContentList.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/Detail/MyDetailTitle.jsx
  client/src/components/My/MyAccount.jsx
  client/src/components/My/MyPageList.jsx
  client/src/components/My/Password/PasswordList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/BasicButton.jsx
  client/src/components/UI/Button/EditButton.jsx
  client/src/components/UI/Button/MyPageButton.jsx
  client/src/components/UI/Button/PostButton.jsx
  client/src/components/UI/DisplayName/DisplayName.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/components/layouts/Main/Main.jsx
  client/src/components/layouts/Nav/Nav.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/My/MyPage.jsx
  client/src/state/useGymStore.jsx
  client/src/utils/dateFormat.js
Labels: FE

#158 feat: 커뮤니티 전체조회, 상세조회 일부 기능 수정
  client/src/components/Board/Board.jsx
  client/src/components/Board/BoardContentList.jsx
  client/src/components/Board/Comment/CommentBody.jsx
  client/src/components/Board/Comment/CommentList.jsx
  client/src/components/Board/Comment/CommentPost.jsx
  client/src/components/Board/Container/Header.jsx
  client/src/components/Board/Detail/BoardDetail.jsx
  client/src/components/Board/Detail/DetailBody.jsx
  client/src/components/Board/Detail/DetailComment.jsx
  client/src/components/Board/Detail/DetailHeader.jsx
  client/src/components/Board/Detail/DetailTab.jsx
  client/src/components/Board/Detail/DetailTitle.jsx
  client/src/components/Board/Post/BoardPost.jsx
  client/src/components/UI/Button/HeartButton.jsx
  client/src/components/UI/HeartContainer.jsx
  client/src/pages/My/MyPage.jsx
  client/src/utils/dateFormat.js
Labels: FE

#159 fix : 댓글 기능 오류 수정
  back/src/main/java/main012/server/community/controller/CommentController.java
  back/src/main/java/main012/server/community/controller/CommunityController.java
  back/src/main/java/main012/server/community/dto/CommentDto.java
  back/src/main/java/main012/server/community/dto/CommunityDto.java
  back/src/main/java/main012/server/community/mapper/CommunityMapper.java
  back/src/main/java/main012/server/community/service/CommentService.java
  back/src/main/java/main012/server/community/service/CommunityService.java
Labels: BE

#161 Fix: 헬스장 전체 조회 수정
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
Labels: BE

#162 feat : 커뮤니티, 댓글 삭제 본인과 관리자만 가능하도록 기능 추가
  back/src/main/java/main012/server/community/service/CommentService.java
  back/src/main/java/main012/server/community/service/CommunityService.java
Labels: BE

#163 Feat: 헬스장 목록 거리순 조회
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/dto/GymWithDistance.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
Labels: BE

#167 Fix: 위도, 경도 Double 로 변경
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/service/GymService.java
Labels: BE

#169 Feat: 헬스장 목록 필터링
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymWithDistance.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
Labels: BE

#170 feat: 리뷰등록, 조회, 수정기능 구현
  client/src/components/Gym/Detail/DetailList.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/Post/PostAddress.jsx
  client/src/components/Gym/Post/PostDetailPrice.jsx
  client/src/components/Gym/Post/PostFacilitiesTagList.jsx
  client/src/components/Gym/Post/PostHours.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Post/PostImageList.jsx
  client/src/components/Gym/Post/PostName.jsx
  client/src/components/Gym/Post/PostPhoneNumber.jsx
  client/src/components/Gym/Post/PostPrice.jsx
  client/src/components/Gym/Review/Review.jsx
  client/src/components/Gym/Review/ReviewConmment.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/Gym/Review/ReviewScore.jsx
  client/src/components/Gym/Review/ReviewTitle.jsx
  client/src/components/UI/Button/MoreButton.jsx
  client/src/components/UI/Button/PostButton.jsx
  client/src/components/UI/More.jsx
  client/src/components/UI/Postcode.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Gym/GymPatch.jsx
  client/src/pages/Gym/GymPost.jsx
  client/src/pages/Home/Home.jsx
  client/src/state/useGymStore.jsx
  client/src/state/useMyStore.jsx
  client/src/state/useStore.jsx
  client/src/utils/api.jsx
Labels: FE

#171 feat: 헬스장 전체조회, 등록기능 수정
  client/src/components/Gym/List/GymTabList.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/components/Gym/Review/ReviewScoreList.jsx
  client/src/components/UI/Button/TabButton.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymPost.jsx
Labels: FE

#172 feat: 위치기반 서비스 구현
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Home/Home.jsx
  client/src/utils/useGeoLocation.jsx
Labels: FE

#173 feat: 마이페이지 프로필 수정 기능 구현중
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/MyAccount.jsx
  client/src/components/My/MyPageList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/layouts/Modal/Modal.jsx
  client/src/pages/My/MyPage.jsx
Labels: FE

#174 feat: 헬스장 필터, 찜 기능구현
  client/public/index.html
  client/src/components/Gym/Detail/DetailHeader.jsx
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/List/GymTabList.jsx
  client/src/components/Gym/Newest/GymNewest.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/components/Gym/Review/Review.jsx
  client/src/components/Gym/Review/ReviewConmment.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/UI/Button/HeartButton.jsx
  client/src/components/UI/Button/TabButton.jsx
  client/src/components/UI/HeartContainer.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
Labels: FE

#175 Style: 로그 추가, 코드 정리
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/service/GymService.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Labels: BE

#176 Feat: 헬스장별 리뷰 목록 조회
  back/src/main/java/main012/server/gym/controller/GymReviewController.java
  back/src/main/java/main012/server/gym/dto/GymReviewDto.java
  back/src/main/java/main012/server/gym/entity/GymReview.java
  back/src/main/java/main012/server/gym/mapper/GymReviewMapper.java
  back/src/main/java/main012/server/gym/repository/GymReviewRepository.java
  back/src/main/java/main012/server/gym/service/GymReviewService.java
Labels: BE

#177 feat: 회원탈퇴 기능 구현
  client/src/components/Login/Login.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
  client/src/components/My/Detail/MyDetailTitle.jsx
  client/src/components/My/Password/CheckPasswordList.jsx
  client/src/components/My/Password/PasswordNewCheck.jsx
  client/src/components/layouts/Modal/Modal.jsx
  client/src/utils/api.jsx
Labels: FE

#179 feat: 헬스장 리뷰 구현
  client/src/components/Gym/List/GymTabList.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Post/PostImageList.jsx
  client/src/components/Gym/Review/Review.jsx
  client/src/components/Gym/Review/ReviewConmment.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/ReviewPost.jsx
  client/src/components/Gym/Review/ReviewScore.jsx
  client/src/components/Gym/Review/ReviewScoreList.jsx
  client/src/components/Gym/Review/ReviewTitle.jsx
  client/src/components/UI/Button/HeartButton.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymDetail.jsx
  client/src/pages/Gym/GymPost.jsx
Labels: FE

#180 feat: 카카오맵 관련
  client/public/index.html
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/UI/Postcode.jsx
Labels: FE

#181 feat: 비밀번호 수정 기능구현
  client/src/components/My/Password/PasswordList.jsx
  client/src/components/My/Profile.jsx
Labels: FE

#182 Fix: 헬스장 수정, 헬스장 상세 조회
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/entity/Gym.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
Labels: BE

#184 feat: 헬스장 리뷰삭제, 찜 기능 구현
  client/src/components/Gym/Gym.jsx
  client/src/components/Gym/List/GymList.jsx
  client/src/components/Gym/List/GymTagList.jsx
  client/src/components/Gym/Map/MapContainer.jsx
  client/src/components/Gym/Review/Review.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/UI/Button/HeartButton.jsx
  client/src/components/UI/HeartContainer.jsx
  client/src/pages/Gym/GymDetail.jsx
Labels: FE

#185 Fix: 코드 수정
  back/src/main/java/main012/server/gym/controller/GymReviewController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/dto/GymReviewDto.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/mapper/GymReviewMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
Labels: BE

#187 Fix: 이미지 RequestPart require false
  back/src/main/java/main012/server/gym/controller/GymController.java
  back/src/main/java/main012/server/gym/dto/GymDto.java
  back/src/main/java/main012/server/gym/mapper/GymMapper.java
  back/src/main/java/main012/server/gym/service/GymService.java
  back/src/main/java/main012/server/user/controller/MemberController.java
  back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Labels: bug, BE

#188 feat: 헬스장 수정구현
  client/src/components/Board/Board.jsx
  client/src/components/Gym/Newest/GymNewestList.jsx
  client/src/components/Gym/Post/PostFacilities.jsx
  client/src/components/Gym/Post/PostFacilitiesTagList.jsx
  client/src/components/Gym/Post/PostImage.jsx
  client/src/components/Gym/Review/Review.jsx
  client/src/components/Gym/Review/ReviewConmment.jsx
  client/src/components/Gym/Review/ReviewList.jsx
  client/src/components/Gym/Review/Reviews.jsx
  client/src/components/UI/Button/BackButton.jsx
  client/src/components/UI/Button/BasicButton.jsx
  client/src/components/UI/Gym/GymPostTag.jsx
  client/src/components/UI/More.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/Gym/Gym.jsx
  client/src/pages/Gym/GymPost.jsx
  client/src/state/useGymStore.jsx
Labels: FE

#189 Fix: 커뮤니티 게시판 수정
  client/src/components/Board/Board.jsx
  client/src/components/Board/BoardContentList.jsx
  client/src/components/Board/Comment/Comment.jsx
  client/src/components/Board/Comment/CommentBody.jsx
  client/src/components/Board/Comment/CommentHeader.jsx
  client/src/components/Board/Comment/CommentList.jsx
  client/src/components/Board/Comment/CommentPost.jsx
  client/src/components/Board/Container/Header.jsx
  client/src/components/Board/Detail/BoardDetail.jsx
  client/src/components/Board/Detail/DetailHeader.jsx
  client/src/components/Board/Post/BoardPost.jsx
  client/src/components/Board/Tab/TabList.jsx
  client/src/components/Board/Tab/TabListItem.jsx
  client/src/components/Login/Login.jsx
  client/src/components/My/Password/PasswordList.jsx
  client/src/components/My/Profile.jsx
  client/src/components/UI/Button/BackButton.jsx
  client/src/components/UI/Button/HeartButton.jsx
  client/src/components/UI/Button/TabButton.jsx
  client/src/components/layouts/Header/Header.jsx
  client/src/pages/Board/Board.jsx
  client/src/state/useBoardStore.jsx
Labels: FE

#190 fix: 마이페이지 헬스장찜목록 수정
  client/src/components/My/Detail/MyDetailList.jsx
  client/src/components/My/Detail/MyDetailListItem.jsx
Labels: FE

#191 fix : 응답 수정 및 게시글 등록 부분 코드 수정
  back/src/main/java/main012/server/community/controller/CommunityController.java
  back/src/main/java/main012/server/community/dto/CommunityDto.java
  back/src/main/java/main012/server/community/service/CommunityService.java
  back/src/main/java/main012/server/gym/entity/GymReview.java
  back/src/main/resources/data.sql
Labels: BE

#193 fix: 마이페이지 프로필수정 기능 수정
  client/src/components/Login/Login.jsx
  client/src/components/My/MyAccount.jsx
  client/src/components/My/Profile.jsx
  client/src/components/SignUp/SignUp.jsx
Labels: FE

#195 fix:오류 수정
  client/src/components/UI/Button/HeartButton.jsx
Labels: FE
